services:
  db:
    image: postgres:16
    container_name: astral-postgres
    environment:
      POSTGRES_DB: astral_db
      POSTGRES_USER: astral_user
      POSTGRES_PASSWORD: astral_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scoring:
    build:
      context: ./scoring-service
      dockerfile: Astral.Scoring.Api/Dockerfile
    container_name: astral-scoring
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5090:8080"

volumes:
  postgres_data: