# Generated by Django 6.0.5 on 2026-05-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearEarthObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasa_jpl_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('absolute_magnitude_h', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('estimated_diameter_min_km', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('estimated_diameter_max_km', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_potentially_hazardous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CloseApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_approach_date', models.DateField()),
                ('epoch_date_close_approach', models.BigIntegerField(blank=True, null=True)),
                ('relative_velocity_kps', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('miss_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('orbiting_body', models.CharField(default='Earth', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('near_earth_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_approaches', to='neos.nearearthobject')),
            ],
            options={
                'ordering': ['close_approach_date'],
            },
        ),
    ]
