# Generated by Django 6.0.5 on 2026-06-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('partial_success', 'Partial success')], default='started', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('started_at', models.DateField(auto_now_add=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('records_requested', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='nearearthobject',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closeapproach',
            name='epoch_date_close_approach',
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='closeapproach',
            constraint=models.UniqueConstraint(fields=('near_earth_object', 'epoch_date_close_approach', 'orbiting_body'), name='unique_close_approach_per_object_epoch_body'),
        ),
    ]
