# Generated by Django 6.0.5 on 2026-06-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos', '0002_apisyncrun_nearearthobject_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisyncrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apisyncrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
