# Generated by Django 6.0.5 on 2026-07-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos', '0003_alter_apisyncrun_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearearthobject',
            name='is_potentially_hazardous',
            field=models.BooleanField(),
        ),
    ]
