# Generated by Django 6.0.5 on 2026-07-21 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos', '0004_alter_nearearthobject_is_potentially_hazardous'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstralScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('Low Interest', 'Low Interest'), ('Moderate Interest', 'Moderate Interest'), ('High Interest', 'High Interest'), ('Critical Review', 'Critical Review')], max_length=32)),
                ('model_version', models.CharField(max_length=32)),
                ('diameter_factor', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('distance_factor', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('velocity_factor', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('timing_factor', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('hazard_flag_factor', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('close_approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='neos.closeapproach')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('close_approach', 'model_version'), name='unique_score_per_approach_model_version')],
            },
        ),
    ]
