# Generated by Django 6.0.5 on 2026-08-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos', '0005_astralscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_type', models.CharField(choices=[('technical', 'Technical')], max_length=32)),
                ('provider', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=32)),
                ('plain_english_summary', models.TextField()),
                ('technical_summary', models.TextField()),
                ('risk_context', models.TextField()),
                ('data_caveats', models.JSONField(default=list)),
                ('source_data_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('astral_score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefings', to='neos.astralscore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
